import type { Anime, Genre, Manga } from './types';

export const mockGenres: Genre[] = [
  { id: '1', name: 'Action', description: 'High energy combat and adventure' },
  { id: '2', name: 'Adventure', description: 'Journeys and exploration' },
  { id: '3', name: 'Comedy', description: 'Humor and funny situations' },
  { id: '4', name: 'Drama', description: 'Emotional and serious themes' },
  { id: '5', name: 'Fantasy', description: 'Magic and supernatural elements' },
  { id: '6', name: 'Romance', description: 'Love and relationships' },
  {
    id: '7',
    name: 'Sci-Fi',
    description: 'Science fiction and futuristic themes',
  },
  { id: '8', name: 'Slice of Life', description: 'Everyday life experiences' },
  { id: '9', name: 'Supernatural', description: 'Paranormal and otherworldly' },
  { id: '10', name: 'Thriller', description: 'Suspense and mystery' },
];

export const mockAnime: Anime[] = [
  {
    id: '1',
    title: 'Attack on Titan',
    synopsis: 'Humanity fights for survival against giant humanoid Titans.',
    genres: ['Action', 'Drama', 'Fantasy'],
    status: 'completed',
    episodes: [
      {
        id: '1-1',
        animeId: '1',
        number: 1,
        title: 'To You, in 2000 Years',
        description: 'Introduction to the world of Titans',
        duration: 1440, // 24 minutes in seconds
        thumbnail: 'https://via.placeholder.com/320x180?text=Episode+1',
        videoUrl: 'mock://video/aot-ep1',
        releaseDate: '2013-04-07',
        watched: false,
        watchProgress: 0,
      },
      {
        id: '1-2',
        animeId: '1',
        number: 2,
        title: 'That Day',
        description: 'The fall of Wall Maria',
        duration: 1440,
        thumbnail: 'https://via.placeholder.com/320x180?text=Episode+2',
        videoUrl: 'mock://video/aot-ep2',
        releaseDate: '2013-04-14',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 87,
    rating: 9.0,
    coverImage: 'https://via.placeholder.com/300x400?text=Attack+on+Titan',
    bannerImage:
      'https://via.placeholder.com/800x300?text=Attack+on+Titan+Banner',
    releaseDate: '2013-04-07',
    studio: 'Wit Studio / MAPPA',
    duration: 24,
    source: 'manga',
  },
  {
    id: '2',
    title: 'Death Note',
    synopsis: 'A high school student discovers a supernatural notebook.',
    genres: ['Supernatural', 'Thriller', 'Drama'],
    status: 'completed',
    episodes: [
      {
        id: '2-1',
        animeId: '2',
        number: 1,
        title: 'Rebirth',
        description: 'Light finds the Death Note',
        duration: 1380, // 23 minutes
        thumbnail: 'https://via.placeholder.com/320x180?text=Death+Note+Ep1',
        videoUrl: 'mock://video/dn-ep1',
        releaseDate: '2006-10-04',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 37,
    rating: 8.6,
    coverImage: 'https://via.placeholder.com/300x400?text=Death+Note',
    bannerImage: 'https://via.placeholder.com/800x300?text=Death+Note+Banner',
    releaseDate: '2006-10-04',
    studio: 'Madhouse',
    duration: 23,
    source: 'manga',
  },
  {
    id: '3',
    title: 'One Piece',
    synopsis: 'Monkey D. Luffy explores the Grand Line to become Pirate King.',
    genres: ['Action', 'Adventure', 'Comedy'],
    status: 'ongoing',
    episodes: [
      {
        id: '3-1',
        animeId: '3',
        number: 1,
        title: "I'm Luffy! The Man Who Will Become Pirate King!",
        description: 'Luffy begins his journey',
        duration: 1380,
        thumbnail: 'https://via.placeholder.com/320x180?text=One+Piece+Ep1',
        videoUrl: 'mock://video/op-ep1',
        releaseDate: '1999-10-20',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 1000,
    rating: 8.9,
    coverImage: 'https://via.placeholder.com/300x400?text=One+Piece',
    bannerImage: 'https://via.placeholder.com/800x300?text=One+Piece+Banner',
    releaseDate: '1999-10-20',
    studio: 'Toei Animation',
    duration: 23,
    source: 'manga',
  },
];

export const mockManga: Manga[] = [
  {
    id: '1',
    title: 'Demon Slayer',
    synopsis: 'Tanjiro becomes a demon slayer to save his sister.',
    genres: ['Action', 'Supernatural', 'Drama'],
    status: 'completed',
    chapters: [
      {
        id: '1-1',
        mangaId: '1',
        number: 1,
        title: 'Cruelty',
        pages: [
          {
            id: '1-1-1',
            chapterId: '1-1',
            number: 1,
            imageUrl: 'https://via.placeholder.com/800x1200?text=Page+1',
            width: 800,
            height: 1200,
          },
          {
            id: '1-1-2',
            chapterId: '1-1',
            number: 2,
            imageUrl: 'https://via.placeholder.com/800x1200?text=Page+2',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2016-02-15',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 205,
    rating: 8.7,
    coverImage: 'https://via.placeholder.com/300x400?text=Demon+Slayer',
    bannerImage: 'https://via.placeholder.com/800x300?text=Demon+Slayer+Banner',
    releaseDate: '2016-02-15',
    author: 'Koyoharu Gotouge',
    artist: 'Koyoharu Gotouge',
    demographic: 'shounen',
  },
  {
    id: '2',
    title: 'My Hero Academia',
    synopsis: 'A boy without powers dreams of becoming a hero.',
    genres: ['Action', 'Adventure', 'Comedy'],
    status: 'ongoing',
    chapters: [
      {
        id: '2-1',
        mangaId: '2',
        number: 1,
        title: 'Izuku Midoriya: Origin',
        pages: [
          {
            id: '2-1-1',
            chapterId: '2-1',
            number: 1,
            imageUrl: 'https://via.placeholder.com/800x1200?text=MHA+Page+1',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2014-07-07',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 400,
    rating: 8.5,
    coverImage: 'https://via.placeholder.com/300x400?text=My+Hero+Academia',
    bannerImage: 'https://via.placeholder.com/800x300?text=MHA+Banner',
    releaseDate: '2014-07-07',
    author: 'Kohei Horikoshi',
    artist: 'Kohei Horikoshi',
    demographic: 'shounen',
  },
  {
    id: '3',
    title: 'Naruto',
    synopsis: 'A ninja with a demon fox inside him seeks recognition.',
    genres: ['Action', 'Adventure', 'Drama'],
    status: 'completed',
    chapters: [
      {
        id: '3-1',
        mangaId: '3',
        number: 1,
        title: 'Uzumaki Naruto',
        pages: [
          {
            id: '3-1-1',
            chapterId: '3-1',
            number: 1,
            imageUrl: 'https://via.placeholder.com/800x1200?text=Naruto+Page+1',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '1999-09-21',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 700,
    rating: 8.8,
    coverImage: 'https://via.placeholder.com/300x400?text=Naruto',
    bannerImage: 'https://via.placeholder.com/800x300?text=Naruto+Banner',
    releaseDate: '1999-09-21',
    author: 'Masashi Kishimoto',
    artist: 'Masashi Kishimoto',
    demographic: 'shounen',
  },
];
