import type { Anime, Genre, Manga } from './types';

export const mockGenres: Genre[] = [
  { id: '1', name: 'Action', description: 'High energy combat and adventure' },
  { id: '2', name: 'Adventure', description: 'Journeys and exploration' },
  { id: '3', name: 'Comedy', description: 'Humor and funny situations' },
  { id: '4', name: 'Drama', description: 'Emotional and serious themes' },
  { id: '5', name: 'Fantasy', description: 'Magic and supernatural elements' },
  { id: '6', name: 'Romance', description: 'Love and relationships' },
  {
    id: '7',
    name: 'Sci-Fi',
    description: 'Science fiction and futuristic themes',
  },
  { id: '8', name: 'Slice of Life', description: 'Everyday life experiences' },
  { id: '9', name: 'Supernatural', description: 'Paranormal and otherworldly' },
  { id: '10', name: 'Thriller', description: 'Suspense and mystery' },
];

export const mockAnime: Anime[] = [
  {
    id: '1',
    title: 'Attack on Titan',
    synopsis:
      'Humanity fights for survival against giant humanoid Titans in a world where they live behind massive walls.',
    genres: ['Action', 'Drama', 'Fantasy'],
    status: 'completed',
    episodes: [
      {
        id: '1-1',
        animeId: '1',
        number: 1,
        title: 'To You, in 2000 Years',
        description: 'Introduction to the world of Titans',
        duration: 1440,
        thumbnail: 'https://pic.re/image/400x225/aot-ep1',
        videoUrl: 'mock://video/aot-ep1',
        releaseDate: '2013-04-07',
        watched: false,
        watchProgress: 0,
      },
      {
        id: '1-2',
        animeId: '1',
        number: 2,
        title: 'That Day',
        description: 'The fall of Wall Maria',
        duration: 1440,
        thumbnail: 'https://pic.re/image/400x225/aot-ep2',
        videoUrl: 'mock://video/aot-ep2',
        releaseDate: '2013-04-14',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 87,
    rating: 9.0,
    coverImage: 'https://pic.re/image/300x400/attack-on-titan',
    bannerImage: 'https://pic.re/image/800x450/aot-banner',
    releaseDate: '2013-04-07',
    studio: 'Wit Studio / MAPPA',
    duration: 24,
    source: 'manga',
  },
  {
    id: '2',
    title: 'Death Note',
    synopsis:
      'A high school student discovers a supernatural notebook that can kill anyone whose name is written in it.',
    genres: ['Supernatural', 'Thriller', 'Drama'],
    status: 'completed',
    episodes: [
      {
        id: '2-1',
        animeId: '2',
        number: 1,
        title: 'Rebirth',
        description: 'Light finds the Death Note',
        duration: 1380,
        thumbnail: 'https://pic.re/image/400x225/death-note-ep1',
        videoUrl: 'mock://video/dn-ep1',
        releaseDate: '2006-10-04',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 37,
    rating: 8.6,
    coverImage: 'https://pic.re/image/300x400/death-note',
    bannerImage: 'https://pic.re/image/800x450/death-note-banner',
    releaseDate: '2006-10-04',
    studio: 'Madhouse',
    duration: 23,
    source: 'manga',
  },
  {
    id: '3',
    title: 'One Piece',
    synopsis:
      'Monkey D. Luffy explores the Grand Line with his crew to become the Pirate King.',
    genres: ['Action', 'Adventure', 'Comedy'],
    status: 'ongoing',
    episodes: [
      {
        id: '3-1',
        animeId: '3',
        number: 1,
        title: "I'm Luffy! The Man Who Will Become Pirate King!",
        description: 'Luffy begins his journey',
        duration: 1380,
        thumbnail: 'https://pic.re/image/400x225/one-piece-ep1',
        videoUrl: 'mock://video/op-ep1',
        releaseDate: '1999-10-20',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 1000,
    rating: 8.9,
    coverImage: 'https://pic.re/image/300x400/one-piece',
    bannerImage: 'https://pic.re/image/800x450/one-piece-banner',
    releaseDate: '1999-10-20',
    studio: 'Toei Animation',
    duration: 23,
    source: 'manga',
  },
  {
    id: '4',
    title: 'Demon Slayer',
    synopsis:
      'Tanjiro becomes a demon slayer to save his sister and avenge his family.',
    genres: ['Action', 'Supernatural', 'Drama'],
    status: 'completed',
    episodes: [
      {
        id: '4-1',
        animeId: '4',
        number: 1,
        title: 'Cruelty',
        description: "Tanjiro's family is attacked by demons",
        duration: 1380,
        thumbnail: 'https://pic.re/image/400x225/demon-slayer-ep1',
        videoUrl: 'mock://video/ds-ep1',
        releaseDate: '2019-04-06',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 44,
    rating: 8.7,
    coverImage: 'https://pic.re/image/300x400/demon-slayer',
    bannerImage: 'https://pic.re/image/800x450/demon-slayer-banner',
    releaseDate: '2019-04-06',
    studio: 'Ufotable',
    duration: 23,
    source: 'manga',
  },
  {
    id: '5',
    title: 'Jujutsu Kaisen',
    synopsis:
      'Students at Tokyo Jujutsu High School learn to fight cursed spirits.',
    genres: ['Action', 'Supernatural', 'School'],
    status: 'ongoing',
    episodes: [
      {
        id: '5-1',
        animeId: '5',
        number: 1,
        title: 'Ryomen Sukuna',
        description: 'Yuji encounters cursed spirits',
        duration: 1380,
        thumbnail: 'https://pic.re/image/400x225/jujutsu-kaisen-ep1',
        videoUrl: 'mock://video/jjk-ep1',
        releaseDate: '2020-10-03',
        watched: false,
        watchProgress: 0,
      },
    ],
    totalEpisodes: 24,
    rating: 8.8,
    coverImage: 'https://pic.re/image/300x400/jujutsu-kaisen',
    bannerImage: 'https://pic.re/image/800x450/jujutsu-kaisen-banner',
    releaseDate: '2020-10-03',
    studio: 'MAPPA',
    duration: 23,
    source: 'manga',
  },
];

export const mockManga: Manga[] = [
  {
    id: '1',
    title: 'Chainsaw Man',
    synopsis:
      'Denji merges with his pet devil to become Chainsaw Man and hunt devils.',
    genres: ['Action', 'Supernatural', 'Horror'],
    status: 'ongoing',
    chapters: [
      {
        id: '1-1',
        mangaId: '1',
        number: 1,
        title: 'Dog & Chainsaw',
        pages: [
          {
            id: '1-1-1',
            chapterId: '1-1',
            number: 1,
            imageUrl: 'https://pic.re/image/800x1200/chainsaw-man-page1',
            width: 800,
            height: 1200,
          },
          {
            id: '1-1-2',
            chapterId: '1-1',
            number: 2,
            imageUrl: 'https://pic.re/image/800x1200/chainsaw-man-page2',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2018-12-03',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 97,
    rating: 8.9,
    coverImage: 'https://pic.re/image/300x400/chainsaw-man',
    bannerImage: 'https://pic.re/image/800x450/chainsaw-man-banner',
    releaseDate: '2018-12-03',
    author: 'Tatsuki Fujimoto',
    artist: 'Tatsuki Fujimoto',
    demographic: 'shounen',
  },
  {
    id: '2',
    title: 'My Hero Academia',
    synopsis:
      'A boy without powers dreams of becoming a hero in a world full of superheroes.',
    genres: ['Action', 'Adventure', 'School'],
    status: 'ongoing',
    chapters: [
      {
        id: '2-1',
        mangaId: '2',
        number: 1,
        title: 'Izuku Midoriya: Origin',
        pages: [
          {
            id: '2-1-1',
            chapterId: '2-1',
            number: 1,
            imageUrl: 'https://pic.re/image/800x1200/my-hero-academia-page1',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2014-07-07',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 400,
    rating: 8.5,
    coverImage: 'https://pic.re/image/300x400/my-hero-academia',
    bannerImage: 'https://pic.re/image/800x450/my-hero-academia-banner',
    releaseDate: '2014-07-07',
    author: 'Kohei Horikoshi',
    artist: 'Kohei Horikoshi',
    demographic: 'shounen',
  },
  {
    id: '3',
    title: 'Tokyo Ghoul',
    synopsis:
      'A college student becomes a half-ghoul and must navigate between human and ghoul worlds.',
    genres: ['Action', 'Horror', 'Supernatural'],
    status: 'completed',
    chapters: [
      {
        id: '3-1',
        mangaId: '3',
        number: 1,
        title: 'Tragedy',
        pages: [
          {
            id: '3-1-1',
            chapterId: '3-1',
            number: 1,
            imageUrl: 'https://pic.re/image/800x1200/tokyo-ghoul-page1',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2011-09-08',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 143,
    rating: 8.3,
    coverImage: 'https://pic.re/image/300x400/tokyo-ghoul',
    bannerImage: 'https://pic.re/image/800x450/tokyo-ghoul-banner',
    releaseDate: '2011-09-08',
    author: 'Sui Ishida',
    artist: 'Sui Ishida',
    demographic: 'seinen',
  },
  {
    id: '4',
    title: 'Spy x Family',
    synopsis:
      'A spy, an assassin, and a telepath form a fake family for their respective missions.',
    genres: ['Comedy', 'Action', 'Slice of Life'],
    status: 'ongoing',
    chapters: [
      {
        id: '4-1',
        mangaId: '4',
        number: 1,
        title: 'Operation Strix',
        pages: [
          {
            id: '4-1-1',
            chapterId: '4-1',
            number: 1,
            imageUrl: 'https://pic.re/image/800x1200/spy-x-family-page1',
            width: 800,
            height: 1200,
          },
        ],
        releaseDate: '2019-03-25',
        read: false,
        readProgress: 0,
      },
    ],
    totalChapters: 80,
    rating: 8.6,
    coverImage: 'https://pic.re/image/300x400/spy-x-family',
    bannerImage: 'https://pic.re/image/800x450/spy-x-family-banner',
    releaseDate: '2019-03-25',
    author: 'Tatsuya Endo',
    artist: 'Tatsuya Endo',
    demographic: 'shounen',
  },
];
